name: BuildCI
on: [push]
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}

      - name: yarn install, yarn lint, yarn test, yarn build
        run: |
          yarn install
          yarn workspace @fndebrid/electron-main compile
          yarn workspace @fndebrid/electron-renderer compile
