name: push-redux-proxy
on:
  push:
    paths:
      - 'packages/electron-redux-proxy/**'
jobs:
  subtree-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run:
          git subtree push --prefix packages/electron-redux-proxy https://${{ secrets.PUSH_TOKEN
          }}@github.com/rhom6us/electron-redux-proxy.git dev
